# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/scp-qt-config.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_configure(object):
    def setupUi(self, configure):
        configure.setObjectName("configure")
        configure.resize(787, 538)
        self.gridLayout_2 = QtWidgets.QGridLayout(configure)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_7 = QtWidgets.QFrame(configure)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.reset = QtWidgets.QPushButton(self.frame_7)
        self.reset.setObjectName("reset")
        self.gridLayout_25.addWidget(self.reset, 0, 1, 1, 1)
        self.close = QtWidgets.QPushButton(self.frame_7)
        self.close.setObjectName("close")
        self.gridLayout_25.addWidget(self.close, 0, 2, 1, 1)
        self.save = QtWidgets.QPushButton(self.frame_7)
        self.save.setObjectName("save")
        self.gridLayout_25.addWidget(self.save, 0, 0, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_25, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_7, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(configure)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 751, 544))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.browse_statementsDB = QtWidgets.QPushButton(self.frame_2)
        self.browse_statementsDB.setObjectName("browse_statementsDB")
        self.gridLayout_7.addWidget(self.browse_statementsDB, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 0, 0, 1, 1)
        self.statementsDB = QtWidgets.QLineEdit(self.frame_2)
        self.statementsDB.setDragEnabled(True)
        self.statementsDB.setClearButtonEnabled(True)
        self.statementsDB.setObjectName("statementsDB")
        self.gridLayout_7.addWidget(self.statementsDB, 0, 1, 1, 1)
        self.beColorful = QtWidgets.QCheckBox(self.frame_2)
        self.beColorful.setObjectName("beColorful")
        self.gridLayout_7.addWidget(self.beColorful, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 1, 0, 1, 1)
        self.statements_tag = QtWidgets.QLineEdit(self.frame_2)
        self.statements_tag.setDragEnabled(True)
        self.statements_tag.setClearButtonEnabled(True)
        self.statements_tag.setObjectName("statements_tag")
        self.gridLayout_7.addWidget(self.statements_tag, 1, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.browse_historyCache = QtWidgets.QPushButton(self.frame_6)
        self.browse_historyCache.setObjectName("browse_historyCache")
        self.gridLayout_15.addWidget(self.browse_historyCache, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setObjectName("label_7")
        self.gridLayout_15.addWidget(self.label_7, 0, 0, 1, 1)
        self.historyCache = QtWidgets.QLineEdit(self.frame_6)
        self.historyCache.setDragEnabled(True)
        self.historyCache.setClearButtonEnabled(True)
        self.historyCache.setObjectName("historyCache")
        self.gridLayout_15.addWidget(self.historyCache, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setObjectName("label_8")
        self.gridLayout_15.addWidget(self.label_8, 1, 0, 1, 1)
        self.maxHistorySize = QtWidgets.QSpinBox(self.frame_6)
        self.maxHistorySize.setMaximum(999999999)
        self.maxHistorySize.setProperty("value", 1048576)
        self.maxHistorySize.setObjectName("maxHistorySize")
        self.gridLayout_15.addWidget(self.maxHistorySize, 0, 1, 1, 1)
        self.browse_historyFile = QtWidgets.QPushButton(self.frame_6)
        self.browse_historyFile.setObjectName("browse_historyFile")
        self.gridLayout_15.addWidget(self.browse_historyFile, 2, 2, 1, 1)
        self.historyFile = QtWidgets.QLineEdit(self.frame_6)
        self.historyFile.setDragEnabled(True)
        self.historyFile.setClearButtonEnabled(True)
        self.historyFile.setObjectName("historyFile")
        self.gridLayout_15.addWidget(self.historyFile, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setObjectName("label_9")
        self.gridLayout_15.addWidget(self.label_9, 2, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_6, 5, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.icon_tray_path = QtWidgets.QLineEdit(self.frame_4)
        self.icon_tray_path.setDragEnabled(True)
        self.icon_tray_path.setClearButtonEnabled(True)
        self.icon_tray_path.setObjectName("icon_tray_path")
        self.gridLayout_11.addWidget(self.icon_tray_path, 0, 1, 1, 1)
        self.browse_iconTrayPath = QtWidgets.QPushButton(self.frame_4)
        self.browse_iconTrayPath.setObjectName("browse_iconTrayPath")
        self.gridLayout_11.addWidget(self.browse_iconTrayPath, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 0, 0, 1, 1)
        self.browse_app_icon_path = QtWidgets.QPushButton(self.frame_4)
        self.browse_app_icon_path.setObjectName("browse_app_icon_path")
        self.gridLayout_11.addWidget(self.browse_app_icon_path, 1, 2, 1, 1)
        self.app_icon_path = QtWidgets.QLineEdit(self.frame_4)
        self.app_icon_path.setDragEnabled(True)
        self.app_icon_path.setClearButtonEnabled(True)
        self.app_icon_path.setObjectName("app_icon_path")
        self.gridLayout_11.addWidget(self.app_icon_path, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_11.addWidget(self.label_14, 1, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_4, 3, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.useChecksum = QtWidgets.QCheckBox(self.frame_3)
        self.useChecksum.setTristate(False)
        self.useChecksum.setObjectName("useChecksum")
        self.gridLayout_9.addWidget(self.useChecksum, 0, 0, 1, 1)
        self.checksumType = QtWidgets.QComboBox(self.frame_3)
        self.checksumType.setObjectName("checksumType")
        self.gridLayout_9.addWidget(self.checksumType, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 2, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setObjectName("label_6")
        self.gridLayout_13.addWidget(self.label_6, 0, 0, 1, 1)
        self.dateformat = QtWidgets.QLineEdit(self.frame_5)
        self.dateformat.setToolTipDuration(10)
        self.dateformat.setStatusTip("")
        self.dateformat.setAccessibleName("")
        self.dateformat.setDragEnabled(True)
        self.dateformat.setClearButtonEnabled(True)
        self.dateformat.setObjectName("dateformat")
        self.gridLayout_13.addWidget(self.dateformat, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.dateformat_view = QtWidgets.QLabel(self.frame_5)
        self.dateformat_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dateformat_view.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.dateformat_view.setObjectName("dateformat_view")
        self.gridLayout_14.addWidget(self.dateformat_view, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_5, 4, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_10 = QtWidgets.QLabel(self.frame_8)
        self.label_10.setObjectName("label_10")
        self.gridLayout_17.addWidget(self.label_10, 0, 0, 1, 1)
        self.browse_sshDir = QtWidgets.QPushButton(self.frame_8)
        self.browse_sshDir.setObjectName("browse_sshDir")
        self.gridLayout_17.addWidget(self.browse_sshDir, 0, 2, 1, 1)
        self.ssh_dir = QtWidgets.QLineEdit(self.frame_8)
        self.ssh_dir.setDragEnabled(True)
        self.ssh_dir.setClearButtonEnabled(True)
        self.ssh_dir.setObjectName("ssh_dir")
        self.gridLayout_17.addWidget(self.ssh_dir, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        self.label_11.setObjectName("label_11")
        self.gridLayout_17.addWidget(self.label_11, 1, 0, 1, 1)
        self.known_hosts = QtWidgets.QLineEdit(self.frame_8)
        self.known_hosts.setDragEnabled(True)
        self.known_hosts.setClearButtonEnabled(True)
        self.known_hosts.setObjectName("known_hosts")
        self.gridLayout_17.addWidget(self.known_hosts, 1, 1, 1, 1)
        self.browse_knownHosts = QtWidgets.QPushButton(self.frame_8)
        self.browse_knownHosts.setObjectName("browse_knownHosts")
        self.gridLayout_17.addWidget(self.browse_knownHosts, 1, 2, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_8, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.browse_get = QtWidgets.QPushButton(self.frame)
        self.browse_get.setObjectName("browse_get")
        self.gridLayout_5.addWidget(self.browse_get, 1, 2, 1, 1)
        self.defaultDir_send = QtWidgets.QLineEdit(self.frame)
        self.defaultDir_send.setDragEnabled(True)
        self.defaultDir_send.setClearButtonEnabled(True)
        self.defaultDir_send.setObjectName("defaultDir_send")
        self.gridLayout_5.addWidget(self.defaultDir_send, 0, 1, 1, 1)
        self.defaultDir_get = QtWidgets.QLineEdit(self.frame)
        self.defaultDir_get.setDragEnabled(True)
        self.defaultDir_get.setClearButtonEnabled(True)
        self.defaultDir_get.setObjectName("defaultDir_get")
        self.gridLayout_5.addWidget(self.defaultDir_get, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.browse_send = QtWidgets.QPushButton(self.frame)
        self.browse_send.setEnabled(False)
        self.browse_send.setObjectName("browse_send")
        self.gridLayout_5.addWidget(self.browse_send, 0, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.statusColor_ring_bad = QtWidgets.QLabel(self.frame_9)
        self.statusColor_ring_bad.setObjectName("statusColor_ring_bad")
        self.gridLayout_19.addWidget(self.statusColor_ring_bad, 0, 1, 1, 1)
        self.statusColor_core_bad = QtWidgets.QLabel(self.frame_9)
        self.statusColor_core_bad.setObjectName("statusColor_core_bad")
        self.gridLayout_19.addWidget(self.statusColor_core_bad, 1, 1, 1, 1)
        self.select_statusColor_ring_bad = QtWidgets.QPushButton(self.frame_9)
        self.select_statusColor_ring_bad.setObjectName("select_statusColor_ring_bad")
        self.gridLayout_19.addWidget(self.select_statusColor_ring_bad, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_9)
        self.label_12.setObjectName("label_12")
        self.gridLayout_19.addWidget(self.label_12, 0, 0, 1, 1)
        self.select_statusColor_core_bad = QtWidgets.QPushButton(self.frame_9)
        self.select_statusColor_core_bad.setObjectName("select_statusColor_core_bad")
        self.gridLayout_19.addWidget(self.select_statusColor_core_bad, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_9)
        self.label_13.setObjectName("label_13")
        self.gridLayout_19.addWidget(self.label_13, 1, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_19, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_9, 1, 1, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_17 = QtWidgets.QLabel(self.frame_10)
        self.label_17.setObjectName("label_17")
        self.gridLayout_21.addWidget(self.label_17, 1, 0, 1, 1)
        self.statusColor_core_good = QtWidgets.QLabel(self.frame_10)
        self.statusColor_core_good.setObjectName("statusColor_core_good")
        self.gridLayout_21.addWidget(self.statusColor_core_good, 1, 1, 1, 1)
        self.select_statusColor_core_good = QtWidgets.QPushButton(self.frame_10)
        self.select_statusColor_core_good.setObjectName("select_statusColor_core_good")
        self.gridLayout_21.addWidget(self.select_statusColor_core_good, 1, 2, 1, 1)
        self.statusColor_ring_good = QtWidgets.QLabel(self.frame_10)
        self.statusColor_ring_good.setObjectName("statusColor_ring_good")
        self.gridLayout_21.addWidget(self.statusColor_ring_good, 0, 1, 1, 1)
        self.select_statusColor_ring_good = QtWidgets.QPushButton(self.frame_10)
        self.select_statusColor_ring_good.setObjectName("select_statusColor_ring_good")
        self.gridLayout_21.addWidget(self.select_statusColor_ring_good, 0, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_10)
        self.label_16.setObjectName("label_16")
        self.gridLayout_21.addWidget(self.label_16, 0, 0, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_21, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_10, 2, 1, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.statusColor_ring_inProgress = QtWidgets.QLabel(self.frame_11)
        self.statusColor_ring_inProgress.setObjectName("statusColor_ring_inProgress")
        self.gridLayout_23.addWidget(self.statusColor_ring_inProgress, 0, 1, 1, 1)
        self.select_statusColor_core_inProgress = QtWidgets.QPushButton(self.frame_11)
        self.select_statusColor_core_inProgress.setObjectName("select_statusColor_core_inProgress")
        self.gridLayout_23.addWidget(self.select_statusColor_core_inProgress, 1, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_11)
        self.label_20.setObjectName("label_20")
        self.gridLayout_23.addWidget(self.label_20, 0, 0, 1, 1)
        self.select_statusColor_ring_inProgress = QtWidgets.QPushButton(self.frame_11)
        self.select_statusColor_ring_inProgress.setObjectName("select_statusColor_ring_inProgress")
        self.gridLayout_23.addWidget(self.select_statusColor_ring_inProgress, 0, 2, 1, 1)
        self.statusColor_core_inProgress = QtWidgets.QLabel(self.frame_11)
        self.statusColor_core_inProgress.setObjectName("statusColor_core_inProgress")
        self.gridLayout_23.addWidget(self.statusColor_core_inProgress, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_11)
        self.label_21.setObjectName("label_21")
        self.gridLayout_23.addWidget(self.label_21, 1, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_23, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_11, 3, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(configure)
        QtCore.QMetaObject.connectSlotsByName(configure)

    def retranslateUi(self, configure):
        _translate = QtCore.QCoreApplication.translate
        configure.setWindowTitle(_translate("configure", "Dialog"))
        self.reset.setText(_translate("configure", "Reset"))
        self.close.setText(_translate("configure", "Close"))
        self.save.setText(_translate("configure", "Save"))
        self.browse_statementsDB.setText(_translate("configure", "Browse"))
        self.label_3.setText(_translate("configure", "Statements DB"))
        self.beColorful.setText(_translate("configure", "BeColorful"))
        self.label_4.setText(_translate("configure", "BeColorful Tag"))
        self.browse_historyCache.setText(_translate("configure", "Browse"))
        self.label_7.setText(_translate("configure", "Max History File Size"))
        self.label_8.setText(_translate("configure", "History Cache Dir."))
        self.browse_historyFile.setText(_translate("configure", "Browse"))
        self.label_9.setText(_translate("configure", "History File"))
        self.browse_iconTrayPath.setText(_translate("configure", "Browse"))
        self.label_5.setText(_translate("configure", "Tray Icon"))
        self.browse_app_icon_path.setText(_translate("configure", "Browse"))
        self.label_14.setText(_translate("configure", "App. Icon"))
        self.useChecksum.setText(_translate("configure", "Use Checksum"))
        self.label_6.setText(_translate("configure", "Date Format"))
        self.dateformat_view.setText(_translate("configure", "Invalid Date Format!"))
        self.label_10.setText(_translate("configure", "SSH Dir."))
        self.browse_sshDir.setText(_translate("configure", "Browse"))
        self.label_11.setText(_translate("configure", "Known Hosts File"))
        self.browse_knownHosts.setText(_translate("configure", "Browse"))
        self.browse_get.setText(_translate("configure", "Browse"))
        self.label.setText(_translate("configure", "Send Default Dir."))
        self.label_2.setText(_translate("configure", "Get Default Dir."))
        self.browse_send.setText(_translate("configure", "Browse"))
        self.statusColor_ring_bad.setText(_translate("configure", "ColorView"))
        self.statusColor_core_bad.setText(_translate("configure", "ColorView"))
        self.select_statusColor_ring_bad.setText(_translate("configure", "Select"))
        self.label_12.setText(_translate("configure", "Status Color Ring:Bad"))
        self.select_statusColor_core_bad.setText(_translate("configure", "Select"))
        self.label_13.setText(_translate("configure", "Status Color Core:Bad"))
        self.label_17.setText(_translate("configure", "Status Color Core:Good"))
        self.statusColor_core_good.setText(_translate("configure", "ColorView"))
        self.select_statusColor_core_good.setText(_translate("configure", "Select"))
        self.statusColor_ring_good.setText(_translate("configure", "ColorView"))
        self.select_statusColor_ring_good.setText(_translate("configure", "Select"))
        self.label_16.setText(_translate("configure", "Status Color Ring:Good"))
        self.statusColor_ring_inProgress.setText(_translate("configure", "ColorView"))
        self.select_statusColor_core_inProgress.setText(_translate("configure", "Select"))
        self.label_20.setText(_translate("configure", "Status Color Ring:InProgress"))
        self.select_statusColor_ring_inProgress.setText(_translate("configure", "Select"))
        self.statusColor_core_inProgress.setText(_translate("configure", "ColorView"))
        self.label_21.setText(_translate("configure", "Status Color Core:InProgress"))

