# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/entryView.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_entryView(object):
    def setupUi(self, entryView):
        entryView.setObjectName("entryView")
        entryView.resize(537, 307)
        self.gridLayout_2 = QtWidgets.QGridLayout(entryView)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(entryView)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 250))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.load = QtWidgets.QPushButton(self.frame)
        self.load.setMinimumSize(QtCore.QSize(100, 50))
        self.load.setMaximumSize(QtCore.QSize(100, 50))
        self.load.setObjectName("load")
        self.gridLayout_3.addWidget(self.load, 0, 0, 1, 1)
        self.remove = QtWidgets.QPushButton(self.frame)
        self.remove.setMinimumSize(QtCore.QSize(100, 50))
        self.remove.setObjectName("remove")
        self.gridLayout_3.addWidget(self.remove, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 2, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.frame)
        self.treeWidget.setMinimumSize(QtCore.QSize(300, 150))
        self.treeWidget.setMaximumSize(QtCore.QSize(200, 150))
        self.treeWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.treeWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.treeWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.treeWidget.setDragEnabled(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout.addWidget(self.treeWidget, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(entryView)
        QtCore.QMetaObject.connectSlotsByName(entryView)

    def retranslateUi(self, entryView):
        _translate = QtCore.QCoreApplication.translate
        entryView.setWindowTitle(_translate("entryView", "Dialog"))
        self.groupBox.setTitle(_translate("entryView", "E: {}"))
        self.load.setText(_translate("entryView", "Load"))
        self.remove.setText(_translate("entryView", "remove"))
        self.treeWidget.headerItem().setText(0, _translate("entryView", "Name"))
        self.treeWidget.headerItem().setText(1, _translate("entryView", "Config"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("entryView", "get"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("entryView", "host"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("entryView", "port"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("entryView", "user"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("entryView", "hostKey"))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("entryView", "useHostKey"))
        self.treeWidget.topLevelItem(0).child(5).setText(0, _translate("entryView", "sources"))
        self.treeWidget.topLevelItem(0).child(6).setText(0, _translate("entryView", "destination"))
        self.treeWidget.topLevelItem(0).child(7).setText(0, _translate("entryView", "remote_home"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("entryView", "send"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("entryView", "host"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("entryView", "port"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("entryView", "user"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("entryView", "hostKey"))
        self.treeWidget.topLevelItem(1).child(4).setText(0, _translate("entryView", "useHostKey"))
        self.treeWidget.topLevelItem(1).child(5).setText(0, _translate("entryView", "sources"))
        self.treeWidget.topLevelItem(1).child(6).setText(0, _translate("entryView", "destination"))
        self.treeWidget.topLevelItem(1).child(7).setText(0, _translate("entryView", "remote_home"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)

