# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/genRSA.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_genRSA(object):
    def setupUi(self, genRSA):
        genRSA.setObjectName("genRSA")
        genRSA.resize(605, 485)
        self.gridLayout_2 = QtWidgets.QGridLayout(genRSA)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(genRSA)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 583, 432))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.privateKey = QtWidgets.QLineEdit(self.groupBox_2)
        self.privateKey.setDragEnabled(True)
        self.privateKey.setClearButtonEnabled(True)
        self.privateKey.setObjectName("privateKey")
        self.gridLayout_7.addWidget(self.privateKey, 0, 1, 1, 1)
        self.browse_privateKey = QtWidgets.QPushButton(self.groupBox_2)
        self.browse_privateKey.setObjectName("browse_privateKey")
        self.gridLayout_7.addWidget(self.browse_privateKey, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 3, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.publicKey = QtWidgets.QLineEdit(self.groupBox)
        self.publicKey.setDragEnabled(True)
        self.publicKey.setClearButtonEnabled(True)
        self.publicKey.setObjectName("publicKey")
        self.gridLayout_9.addWidget(self.publicKey, 0, 1, 1, 1)
        self.browse_publicKey = QtWidgets.QPushButton(self.groupBox)
        self.browse_publicKey.setObjectName("browse_publicKey")
        self.gridLayout_9.addWidget(self.browse_publicKey, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 5, 2, 1, 1)
        self.groupBox1 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox1.setObjectName("groupBox1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.keysize = QtWidgets.QSpinBox(self.groupBox1)
        self.keysize.setMinimum(2048)
        self.keysize.setMaximum(999999999)
        self.keysize.setObjectName("keysize")
        self.gridLayout_5.addWidget(self.keysize, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox1)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 1, 0, 1, 1)
        self.encrypted = QtWidgets.QCheckBox(self.groupBox1)
        self.encrypted.setObjectName("encrypted")
        self.gridLayout_5.addWidget(self.encrypted, 2, 0, 1, 1)
        self.passphrase = QtWidgets.QLineEdit(self.groupBox1)
        self.passphrase.setEnabled(False)
        self.passphrase.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.passphrase.setDragEnabled(True)
        self.passphrase.setClearButtonEnabled(True)
        self.passphrase.setObjectName("passphrase")
        self.gridLayout_5.addWidget(self.passphrase, 2, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox1, 2, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.close = QtWidgets.QPushButton(self.frame)
        self.close.setMinimumSize(QtCore.QSize(0, 50))
        self.close.setMaximumSize(QtCore.QSize(16777215, 50))
        self.close.setObjectName("close")
        self.gridLayout_11.addWidget(self.close, 0, 1, 1, 1)
        self.generate = QtWidgets.QPushButton(self.frame)
        self.generate.setMinimumSize(QtCore.QSize(0, 50))
        self.generate.setMaximumSize(QtCore.QSize(16777215, 50))
        self.generate.setObjectName("generate")
        self.gridLayout_11.addWidget(self.generate, 0, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(genRSA)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(genRSA)
        QtCore.QMetaObject.connectSlotsByName(genRSA)

    def retranslateUi(self, genRSA):
        _translate = QtCore.QCoreApplication.translate
        genRSA.setWindowTitle(_translate("genRSA", "Dialog"))
        self.groupBox_2.setTitle(_translate("genRSA", "Private Key"))
        self.browse_privateKey.setText(_translate("genRSA", "Browse"))
        self.groupBox.setTitle(_translate("genRSA", "Public Key"))
        self.browse_publicKey.setText(_translate("genRSA", "Browse"))
        self.groupBox1.setTitle(_translate("genRSA", "Key Settings"))
        self.label.setText(_translate("genRSA", "Key Size"))
        self.encrypted.setText(_translate("genRSA", "Encrypted"))
        self.close.setText(_translate("genRSA", "Close"))
        self.generate.setText(_translate("genRSA", "Generate"))

